#!/usr/bin/env bash
# This script display "Best School" and on the 9th displays "Hi".

count=0

while [ $count -lt 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Hi"
	fi
	echo "Best School"
	(( count++ ))
done
